/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clase.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        cmdConvertir.setEnabled(false);
                    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtNumerador1 = new javax.swing.JTextField();
        txtDenominador1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        cmboper = new javax.swing.JComboBox<>();
        txtNumerador2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtDenominador2 = new javax.swing.JTextField();
        txtDenominador3 = new javax.swing.JTextField();
        txtNumerador3 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        cmdCalcular = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        cmdConvertir = new javax.swing.JButton();
        txtMx = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Operaciones Con Fraccionarios");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        txtNumerador1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumerador1KeyTyped(evt);
            }
        });
        jPanel4.add(txtNumerador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 60, -1));

        txtDenominador1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDenominador1KeyTyped(evt);
            }
        });
        jPanel4.add(txtDenominador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 60, -1));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, 10));

        cmboper.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sumar", "Restar", "Multiplicar", "Dividir" }));
        jPanel4.add(cmboper, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 70, -1));

        txtNumerador2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumerador2KeyTyped(evt);
            }
        });
        jPanel4.add(txtNumerador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 60, -1));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 60, 10));

        txtDenominador2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDenominador2KeyTyped(evt);
            }
        });
        jPanel4.add(txtDenominador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 60, -1));

        txtDenominador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDenominador3ActionPerformed(evt);
            }
        });
        jPanel4.add(txtDenominador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 60, -1));

        txtNumerador3.setForeground(new java.awt.Color(255, 255, 255));
        txtNumerador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumerador3ActionPerformed(evt);
            }
        });
        jPanel4.add(txtNumerador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 60, -1));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 60, 10));

        jLabel1.setText("=");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 10, 20));

        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel4.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        cmdConvertir.setText("Convertir a mixto");
        cmdConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdConvertirActionPerformed(evt);
            }
        });
        jPanel4.add(cmdConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        txtMx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMxActionPerformed(evt);
            }
        });
        jPanel4.add(txtMx, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(423, 284));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumerador3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumerador3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumerador3ActionPerformed

    private void txtDenominador3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDenominador3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDenominador3ActionPerformed

    private void txtNumerador1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumerador1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumerador1KeyTyped

    private void txtDenominador1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDenominador1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDenominador1KeyTyped

    private void txtNumerador2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumerador2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumerador2KeyTyped

    private void txtDenominador2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDenominador2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDenominador2KeyTyped

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
        try {
            int oper, Num1, Num2, Num3;
            int Den1, Den2, Den3;
            Fraccionario f1, f2, f3 = null;
            
            cmdConvertir.setEnabled(true);
            oper = cmboper.getSelectedIndex();
            Num1 = Integer.parseInt(txtNumerador1.getText());
            Den1 = Integer.parseInt(txtDenominador2.getText());
            Num2 = Integer.parseInt(txtNumerador2.getText());
            Den2 = Integer.parseInt(txtDenominador2.getText());

            f1 = new Fraccionario(Num1, Den1);
            f2 = new Fraccionario(Num2, Den2);

            switch (oper) {
                case 0:
                    f3 = f1.Sumar(f2);
                    break;
                case 1:
                    f3 = f1.Restar(f2);
                    break;
                case 2:
                    f3 = f1.multiplicar(f2);
                    break;
                case 3:
                    f3 = f1.Dividir(f2);
                    break;
            }
            txtNumerador3.setText(""+f3.getNumerador());
            txtDenominador3.setText(""+f3.getDenominador());
            txtMx.setText("");
      
        } catch (DenominadorCeroException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "campos vacios , por favor ingrese el digito", "ERROR", JOptionPane.ERROR_MESSAGE);

            txtNumerador1.setText("");
            txtNumerador2.setText("");
            txtDenominador1.setText("");
            txtDenominador2.setText("");
            txtNumerador3.setText("");
            txtDenominador3.setText("");
            txtNumerador1.requestFocusInWindow();
            cmboper.setSelectedIndex(0);
        }

    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed

        txtNumerador1.setText("");
        txtNumerador2.setText("");
        txtDenominador1.setText("");
        txtDenominador2.setText("");
        txtNumerador3.setText("");
        txtDenominador3.setText("");
        txtMx.setText("");
        txtNumerador1.requestFocusInWindow();
        cmboper.setSelectedIndex(0);
        cmdConvertir.setEnabled(false);
                    

    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdConvertirActionPerformed

        int Num,Den,Mx;
        
        Num=Integer.parseInt(txtNumerador3.getText());
        Den=Integer.parseInt(txtDenominador3.getText());
        
        if(Num > Den){
            Mx= Num/Den;
            
            txtNumerador3.setText(""+(Num%Den));
            txtDenominador3.setText(""+Den);
            txtMx.setText(""+Mx);
            cmdConvertir.setEnabled(false);
                    
        }
        else{
            JOptionPane.showMessageDialog(this,"el resultado debe ser una fraccion impropia para poder hacer la conversion", "INFORMACION",JOptionPane.INFORMATION_MESSAGE);
            cmdConvertir.setEnabled(false);
        }
        
        
        
        
        
    }//GEN-LAST:event_cmdConvertirActionPerformed

    private void txtMxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmboper;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdConvertir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtDenominador1;
    private javax.swing.JTextField txtDenominador2;
    private javax.swing.JTextField txtDenominador3;
    private javax.swing.JTextField txtMx;
    private javax.swing.JTextField txtNumerador1;
    private javax.swing.JTextField txtNumerador2;
    private javax.swing.JTextField txtNumerador3;
    // End of variables declaration//GEN-END:variables
}
